[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Allow Shopify embedding for the embedded route
[[headers]]
  for = "/shopify-embedded*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors *.myshopify.com https://*.shopify.com https://admin.shopify.com"

# Also allow embedding for the root if needed (but with restrictions)
[[headers]]
  for = "/"
  [headers.values]
    Content-Security-Policy = "frame-ancestors *.myshopify.com https://*.shopify.com https://admin.shopify.com"

# Deny framing for admin route (security)
[[headers]]
  for = "/admin"
  [headers.values]
    X-Frame-Options = "DENY"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
